config/routes.rb
Rails.application.routes.draw do
  root 'pokemons#index'
  resources :pokemons, only: [:index, :show]
  resources :shapes, only: [:index, :show]
  resources :types, only: [:index, :show]
  resources :abilities, only: [:index, :show]
  resources :about, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability < ApplicationRecord
  has_and_belongs_to_many :pokemons

  validates :name, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_and_belongs_to_many :types
  has_and_belongs_to_many :abilities
  belongs_to :shape

  validates :name, presence: true, uniqueness: true
  validates :weight, :height, :image, presence: true
end

app/models/shape.rb
class Shape < ApplicationRecord
  has_many :pokemons

  validates :name, presence: true, uniqueness: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_and_belongs_to_many :pokemons

  validates :name, presence: true, uniqueness: true
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  def index
    @abilities = Ability.left_joins(:pokemons)
                        .select('abilities.*, COUNT(pokemons.id) AS pokemon_count')
                        .group('abilities.id')
                        .order('pokemon_count DESC')
                        .page(params[:page]).per(15)
  end

  def show
    @ability = Ability.find(params[:id])
    @pokemons = @ability.pokemons.page(params[:page]).per(15)
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all

    if params[:search].present?
      @pokemons = @pokemons.where("pokemons.name LIKE ?", "%#{params[:search]}%")
    end

    if params[:type].present?
      @pokemons = @pokemons.joins(:types).where(types: { name: params[:type] })
    end

    @pokemons = @pokemons.page(params[:page]).per(15)
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
  end
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
  def index
    @shapes = Shape.left_joins(:pokemons)
                   .select('shapes.*, COUNT(pokemons.id) AS pokemon_count')
                   .group('shapes.id')
                   .order('pokemon_count DESC')
                   .page(params[:page]).per(15)
  end

  def show
    @shape = Shape.find(params[:id])
    @pokemons = @shape.pokemons.page(params[:page]).per(15)
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.left_joins(:pokemons)
                 .select('types.*, COUNT(pokemons.id) AS pokemon_count')
                 .group('types.id')
                 .order('pokemon_count DESC')
                 .page(params[:page]).per(15)
  end

  def show
    @type = Type.find(params[:id])
    @pokemons = @type.pokemons.page(params[:page]).per(15)
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
  end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/abilities/index.html.erb
<h1>Abilities</h1>

<% if @abilities.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Ability</th>
        <th>Number of Pokemons</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @abilities.each do |ability| %>
        <tr>
          <td><%= ability.name.capitalize %></td>
          <td><%= ability.pokemons.count %></td>
          <td><%= link_to 'Show Pokemons', ability_path(ability), class: "btn btn-outline-success" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row mt-4">
    <%= paginate @abilities, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm justify-content-center", nav_class: "d-inline-b" %>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    No abilities found.
  </div>
<% end %>

app/views/abilities/show.html.erb
<h1 class="text-center">Pokemons with <%= @ability.name.capitalize %> Ability</h1>

<% if @pokemons.any? %>
  <div class="row justify-content-center">
    <% @pokemons.each do |pokemon| %>
      <%= render partial: 'shared/pokemon_card', locals: { pokemon: pokemon } %>
    <% end %>
  </div>

  <div class="row mt-4">
    <%= paginate @pokemons, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm justify-content-center", nav_class: "d-inline-b" %>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    No Pokemon found.
  </div>
<% end %>

app/views/about/index.html.erb
<div class="row justify-content-center mb-2">
  <div class="col-md-6">
    <h1>About Us</h1>
    <p>Welcome to PokeData, your ultimate destination for exploring Pokemon data! At PokeData, we provide comprehensive datasets on various aspects of the Pokemon world, including types, abilities, shapes, and individual Pokemon details.</p>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h2>PokeData Datasets</h2>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h3>1.	Type Data:</h3>
    <p>•	<b>URL:</b> https://pokeapi.co/api/v2/type?limit=18</p>
    <p>•	<b>Data Structure:</b> The type data contains information about various Pokemon types.</p>
    <p>•	<b>Database Table:</b> types</p>
    <p>•	<b>Required Columns:</b></p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;o	name (string)</p>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h3>2.	Ability Data:</h3>
    <p>•	<b>URL:</b> https://pokeapi.co/api/v2/ability?limit=307</p>
    <p>•	<b>Data Structure:</b> The ability data contains information about various Pokemon abilities.</p>
    <p>•	<b>Database Table:</b> abilities</p>
    <p>•	<b>Required Columns:</b></p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;o	name (string)</p>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h3>3.	Shape Data:</h3>
    <p>•	<b>URL:</b> https://pokeapi.co/api/v2/pokemon-shape</p>
    <p>•	<b>Data Structure:</b> The shape data contains information about different shapes that Pokemon can have.</p>
    <p>•	<b>Database Table:</b> shapes</p>
    <p>•	<b>Required Columns:</b></p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;o	name (string)</p>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h3>4.	Pokemon Data:</h3>
    <p>•	<b>URL:</b> https://pokeapi.co/api/v2/pokemon/#{pokemon_id}/</p>
    <p>•	<b>Data Structure:</b> The Pokemon data contains details about individual Pokemon, such as name, weight, height, types, abilities, etc.</p>
    <p>•	<b>Database Table:</b> pokemons</p>
    <p>•	<b>Required Columns:</b></p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;o	name (string)</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;o	weight (float)</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;o	height (float)</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;o	image (string)</p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;o	shape_id (foreign key referencing the shapes table)</p>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-md-6">
    <h3>5.	Pokemon Species Data:</h3>
    <p>•	<b>URL:</b> https://pokeapi.co/api/v2/pokemon-species/#{pokemon_id}/</p>
    <p>•	<b>Data Structure:</b> The Pokemon species data provides additional details about a Pokemon species, including the shape.</p>
    <p>•	<b>Database Table:</b> pokemons</p>
    <p>•	<b>Additional Columns in pokemons Table:</b></p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;o	shape_id (foreign key referencing the shapes table)</p>
  </div>
</div>

<div class="row justify-content-center mt-2">
  <div class="col-md-6">
    <p>
      We begin by retrieving data from external APIs for Pokemon types, abilities, and shapes, populating the respective tables with this data.
      Then, we iterate through Pokemon IDs from 1 to 1025, fetching details about each Pokemon and its species.
      Finally, for each Pokemon, we create a record in the Pokemons table, associating it with its shape, types, and abilities.
    </p>
  </div>
</div>

<div class="row justify-content-center mt-3">
  <div class="col-md-6">
    <h2>Entity Relationship Diagram</h2>
    <%= image_tag "/assets/PokeData_ERD.png", class: 'img-responsive w-100', alt: "Entity relationship diagram" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Pokedata</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to "PokeData", root_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
          <ul class="navbar-nav gap-3">
            <li>
              <%= link_to "Pokemons", pokemons_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "Shapes", shapes_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "Types", types_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "Abilities", abilities_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "About Us", about_index_path, class: "nav-link" %>
            </li>
          </ul>

          <form class="form-inline ml-auto" action="<%= pokemons_path %>">
            <div class="input-group">
              <input type="text" class="form-control" name="search" placeholder="Search for Pokemon" aria-label="Search" value="<%= params[:search] %>">

              <div class="input-group-append">
                <select class="form-select rounded-0" name="type">
                  <option value="" <%= "selected" if params[:type].blank? %>>All Types</option>
                  <% Type.all.each do |type| %>
                    <option value="<%= type.name %>" <%= "selected" if params[:type] == type.name %>><%= type.name.capitalize %></option>
                  <% end %>
                </select>
              </div>

              <button class="btn btn-success">Search</button>
            </div>
          </form>
        </div>
      </div>
    </nav>

    <div class="container py-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1 class="text-center">Pokemon List</h1>

<% if @pokemons.any? %>
  <div class="row justify-content-center">
    <% @pokemons.each do |pokemon| %>
      <%= render partial: 'shared/pokemon_card', locals: { pokemon: pokemon } %>
    <% end %>
  </div>

  <div class="row mt-4">
    <%= paginate @pokemons, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm justify-content-center", nav_class: "d-inline-b" %>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    No Pokemon found.
  </div>
<% end %>

app/views/pokemons/show.html.erb
<div class="row justify-content-center">
    <div class="col-md-4">
      <div class="thumbnail d-flex align-items-center gap-5">
        <%= image_tag @pokemon.image, class: 'img-responsive', alt: @pokemon.name %>
        <div class="caption">
          <h3><%= @pokemon.name.capitalize %></h3>

          <p>Weight: <%= @pokemon.weight %> hectograms</p>
          <p>Height: <%= @pokemon.height %> decimetres</p>

          <p>Shape: <%= link_to @pokemon.shape.name, shape_path(@pokemon.shape) %></p>

          <p>Types:
            <% types = @pokemon.types.map { |type| link_to(type.name, type_path(type)) } %>
            <%= types.join(', ').html_safe %>
          </p>

          <p>Abilities:
            <% abilities = @pokemon.abilities.map { |ability| link_to(ability.name, ability_path(ability)) } %>
            <%= abilities.join(', ').html_safe %>
          </p>
        </div>
      </div>
    </div>
</div>

app/views/shapes/index.html.erb
<h1>Shapes</h1>

<% if @shapes.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Shape</th>
        <th>Number of Pokemons</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @shapes.each do |shape| %>
        <tr>
          <td><%= shape.name.capitalize %></td>
          <td><%= shape.pokemons.count %></td>
          <td><%= link_to 'Show Pokemons', shape_path(shape), class: "btn btn-outline-success" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row mt-4">
    <%= paginate @shapes, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm justify-content-center", nav_class: "d-inline-b" %>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    No shapes found.
  </div>
<% end %>

app/views/shapes/show.html.erb
<h1 class="text-center"><%= @shape.name.capitalize %> Pokemons</h1>

<% if @pokemons.any? %>
  <div class="row justify-content-center">
    <% @pokemons.each do |pokemon| %>
      <%= render partial: 'shared/pokemon_card', locals: { pokemon: pokemon } %>
    <% end %>
  </div>

  <div class="row mt-4">
    <%= paginate @pokemons, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm justify-content-center", nav_class: "d-inline-b" %>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    No Pokemon found.
  </div>
<% end %>

app/views/shared/_pokemon_card.html.erb
<div class="col-md-4">
  <div class="thumbnail d-flex flex-column align-items-center">
    <%= image_tag pokemon.image, class: 'img-responsive', alt: pokemon.name %>
    <div class="caption">
      <%= link_to pokemon_path(pokemon) do %>
        <h3><%= pokemon.name.capitalize %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/types/index.html.erb
<h1>Types</h1>

<% if @types.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>Type</th>
        <th>Number of Pokemons</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @types.each do |type| %>
        <tr>
          <td><%= type.name.capitalize %></td>
          <td><%= type.pokemons.count %></td>
          <td><%= link_to 'Show Pokemons', type_path(type), class: "btn btn-outline-success" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row mt-4">
    <%= paginate @types, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm justify-content-center", nav_class: "d-inline-b" %>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    No types found.
  </div>
<% end %>

app/views/types/show.html.erb
<h1 class="text-center"><%= @type.name.capitalize %> Pokemons</h1>

<% if @pokemons.any? %>
  <div class="row justify-content-center">
    <% @pokemons.each do |pokemon| %>
      <%= render partial: 'shared/pokemon_card', locals: { pokemon: pokemon } %>
    <% end %>
  </div>

  <div class="row mt-4">
    <%= paginate @pokemons, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm justify-content-center", nav_class: "d-inline-b" %>
  </div>
<% else %>
  <div class="alert alert-info text-center" role="alert">
    No Pokemon found.
  </div>
<% end %>